### ISSUE TITLE
Remote connection rendering on Windows

### ISSUE THREAD

**Issue by Philistino** [charmbracelet/wishlist#102]
Hello,

Really love the idea of this project! The TUI works great until the connection is made, at which point the terminal of the remote machine is not shown and only a few characters of a typed command can be displayed, if at all. I am running on Windows 10 and I tried the new windows terminal with powershell, normal old cmd prompt, and the powershell terminal.  Screenshots below. 

Thanks for your work on this exciting project and I hope this helps.
 Edit: I built the binary using go 1.18 and I connected using the wishlist command with no flags or positional arguments, selected the host, and hit enter.

<img width="866" alt="Screenshot 2022-07-09 000413" src="https://user-images.githubusercontent.com/67737255/178080376-4d7cc16a-5783-4a61-a7e7-d76ee1d0cc8c.png">
<img width="911" alt="Screenshot 2022-07-09 000128" src="https://user-images.githubusercontent.com/67737255/178080378-865bc25e-23df-4beb-af45-a53b136a71d0.png">

**Comment by imadjamil** [comment]
Same prodlem here, built from source using go version go1.18.4 windows/amd64.

**Comment by caarlos0** [comment]
hmm, just to be sure, a few questions:

- are you running the wishlist in local mode? 
  - if so, are you running it within WSL?
  - if not, is the wishlist server running in Linux or WSL?
- does this issue happens accessing linux machines only?

thanks

**Comment by imadjamil** [comment]
For me, I am just using the "demo" link from your readme ...

**Comment by imadjamil** [comment]
I built it and using it on Windows 10 (no WSl involved)

**Comment by codedotspirit** [comment]
Hey, adding to this. Rendering is messed up only on Windows, it works perfectly fine on my WSL instance. Using the newest release (v0.14.0) via scoop on Windows and installed it on my Kali instance via the method described in the README.
The Windows output looks as follows:

![image](https://github.com/charmbracelet/wishlist/assets/66965600/31c7825d-8643-42b0-a7f1-ed91bebcb64e)

This is the Linux output:

![image](https://github.com/charmbracelet/wishlist/assets/66965600/99f8837c-31f4-4dac-ba0b-d89d0c0457fc)

In both cases, I am connecting to the same server. To answer the previous questions:
1. In both cases, wishlist is running in local mode.
2. No wishlist server instance is running on the server.
3. I have not been able to test if this happens when trying to reach machines that run any other system than Linux.

**Comment by caarlos0** [comment]
thanks for all the info!

can you check if #241 fixes this?

**Comment by codedotspirit** [comment]
I put the screenshot in the PR comments as well, but this is what it looks like when using that branches files to compile the exe file myself:
![image](https://github.com/charmbracelet/wishlist/assets/66965600/e005e88c-cb12-4acc-905b-c8892e85a70a)

**Comment by caarlos0** [comment]
awesome, thank you for verifying 🙏🏻
